module.exports = {

  // Colors for embeds
  BLURPLE: "#7289DA",
  EMBED_COLOR: "#7289DA",
  EMBED_JOIN_COLOR: "#66FF00",
  EMBED_JOIN_WARN_COLOR: "#FFAA1D",
  EMBED_LEAVE_COLOR: "#08E8DE",
  EMBED_KICK_COLOR: "#FFF000",
  EMBED_ROLE_COLOR: "#f1726b",
  EMBED_MSGUPDATE_COLOR: "#bf63a3",
  EMBED_MSGDELETED_COLOR: "#50c0a3",
  EMBED_BANADD_COLOR: "#ff1a4c",
  EMBED_BANRMV_COLOR: "#ff9d00",
  EMBED_MASSPING_COLOR: "#ff1a4c",
  EMBED_CHCREATE_COLOR: "#0000c1",
  EMBED_CHDELETE_COLOR: "#0000c1",
  EMBED_ROLECREATE_COLOR: "#ea07ff",
  EMBED_ROLEDELETE_COLOR: "#ea07ff",
  EMBED_ROLEUPDATE_COLOR: "#ea07ff",
  EMBED_CHUPDATE_COLOR: "#ea07ff",
  EMBED_GUILDCREATE_COLOR: "#50c0a3",
  EMBED_GUILDDELETE_COLOR: "#ff0000",
  EMBED_NOTEADD_COLOR: "YELLOW",
  EMBED_RATELIMIT_COLOR: "#FF0000",
  EMBED_EVAL_ERROR: "#FF0000"
};
