module.exports = {
  //Bot Sharding Status
  CONTROL_CHANNEL_ID: "",
  CONTROL_CHANNEL_WEBHOOK_ID: "",
  CONTROL_CHANNEL_WEBHOOK_SECRET: "",

  //Error-Channel
  ERROR_CHANNEL_WEBHOOK_ID: "",
  ERROR_CHANNEL_WEBHOOK_SECRET: "",

  //Bot Join-Leave Log
  BOT_JOINLEAVE_CHANNEL_WEBHOOK_ID: "",
  BOT_JOINLEAVE_CHANNEL_WEBHOOK_SECRET: "",

  //Vote Logs
  BOT_VOTES_CHANNEL_WEBHOOK_ID: "",
  BOT_VOTES_CHANNEL_WEBHOOK_SECRET: ""
};
